# IMDB Dataset Analysis

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Load the Dataset

In [3]:
df = pd.read_csv("../data/imdb_top_1000.csv.xls")

## Reasearch Question

Examining whether there is a relationship between **Metascore** and **IMDb Rating**.

## Step 1

Checking for **missing** or **null values** in the dataset.

In [ ]:
df[["Meta_score", "IMDB_Rating"]].isnull()

     Meta_score  IMDB_Rating
0          True         True
1          True         True
2          True         True
3          True         True
4          True         True
..          ...          ...
995        True         True
996        True         True
997        True         True
998        True         True
999        True         True

[1000 rows x 2 columns]

## Step 2

Fix Missing Values

In [6]:
not_null_df = df[["Meta_score", "IMDB_Rating"]].notnull()

## Step 3

Check Corration Between IMDB And Metascore

In [9]:
df[["Meta_score", "IMDB_Rating"]].corr()

             Meta_score  IMDB_Rating
Meta_score     1.000000     0.268531
IMDB_Rating    0.268531     1.000000